table Date
	lineageTag: 4ff9be2a-65fa-4950-97f1-ae192c462f9c
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: dd-mmm-yy
		lineageTag: ea4cf969-dd41-4bfa-8ba1-2aa437955d17
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2cefa84a-db34-44e5-95a6-b9bfba826f69
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 95b261ce-9e6c-4b55-8524-d55b9dca8a35
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column MMM
		dataType: string
		lineageTag: 3189a519-53e9-46db-9f29-c10a0a1797bc
		summarizeBy: none
		sourceColumn: MMM

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 23a6a6f1-7d08-443b-8b3e-7e4f12adf0dd
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 80390fd6-92ab-43d6-911b-f171f4649e6c
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column DDD
		dataType: string
		lineageTag: 0fff7d3a-6e28-4425-8178-0cdfad651291
		summarizeBy: none
		sourceColumn: DDD

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: 6850fae7-45e1-430d-89e6-554d0b732633
		summarizeBy: sum
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column YYMM
		dataType: string
		lineageTag: 27f967fd-0423-4578-8dd2-d538bedc6a02
		summarizeBy: none
		sourceColumn: YYMM

		annotation SummarizationSetBy = Automatic

	column MonthID
		dataType: string
		lineageTag: 0b2e1306-cebc-4403-b5e3-48609089c4e8
		summarizeBy: none
		sourceColumn: MonthID

		annotation SummarizationSetBy = Automatic

	partition Date-cfb1007b-e483-4ab3-bbfa-d6dbc7d7a9a6 = m
		mode: import
		queryGroup: 'Add your data to these queries'
		source =
				//Calendar Year
				let
				    Source = List.Dates(StartDate, Length, #duration(1, 0, 0, 0)),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    // Enter the first date that appears in your data in the formula bar at this step. My data starts in 2013, so I entered 1/1/2013. The dates in this table are in US date format.
				    StartDate = #date(2013, 1, 1),
				    Today = Date.EndOfYear(DateTime.Date(DateTime.LocalNow())),
				    Length = Duration.Days(Today - StartDate),
				    Custom1 = #"Changed Type",
				    #"Inserted Year" = Table.AddColumn(Custom1, "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Month Name", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Day Name", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Month", "Day of Week", each Date.DayOfWeek(([Date]), Day.Sunday)+1, Int64.Type),
				    #"Inserted First Characters" = Table.AddColumn(#"Inserted Day of Week", "MMM", each Text.Start([Month Name], 3), type text),
				    #"Inserted First Characters1" = Table.AddColumn(#"Inserted First Characters", "DDD", each Text.Start([Day Name], 3), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Inserted First Characters1",{"Date", "Year", "Month Name", "MMM", "Month", "Day Name", "DDD", "Day of Week"}),
				    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "YYMM", each ([Year]-2000)*100 + [Month]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "MonthID", each (Date.Year([Date]) - Date.Year(StartDate))*12 + Date.Month([Date]))
				in
				    #"Added Custom1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

